package mainMenu;

import static mainMenu.arcadeGUI.getCellRange;

import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;


/*
 * this program will allow the users to change their userNames
 */

/**
 *
 * @author Parker Rowe
 */
public class changeUserNameGUI extends javax.swing.JFrame {

    /**
     * Creates new form changeUserNameGUI
     */
    public changeUserNameGUI() {
        initComponents();
        
        //set the current username text area equal the current user's username global variable
        currentUserNameText.setText(arcadeGUI.userName);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        changeUserNamePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userIDText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        currentUserNameText = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        newUserNameText = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Change Username");

        changeUserNamePanel.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User ID:");

        userIDText.setEditable(false);
        userIDText.setBackground(new java.awt.Color(0, 0, 0));
        userIDText.setForeground(new java.awt.Color(255, 255, 255));
        userIDText.setText(System.getProperty("user.name"));
        userIDText.setBorder(null);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current User Name:");

        currentUserNameText.setEditable(false);
        currentUserNameText.setBackground(new java.awt.Color(0, 0, 0));
        currentUserNameText.setForeground(new java.awt.Color(255, 255, 255));
        currentUserNameText.setBorder(null);
        currentUserNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentUserNameTextActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New User Name:");

        newUserNameText.setBackground(new java.awt.Color(0, 0, 0));
        newUserNameText.setForeground(new java.awt.Color(255, 255, 255));
        newUserNameText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        newUserNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUserNameTextActionPerformed(evt);
            }
        });
        newUserNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                newUserNameTextKeyPressed(evt);
            }
        });

        changeButton.setBackground(new java.awt.Color(0, 0, 0));
        changeButton.setForeground(new java.awt.Color(255, 255, 255));
        changeButton.setText("Change");
        changeButton.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout changeUserNamePanelLayout = new javax.swing.GroupLayout(changeUserNamePanel);
        changeUserNamePanel.setLayout(changeUserNamePanelLayout);
        changeUserNamePanelLayout.setHorizontalGroup(
            changeUserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                .addGroup(changeUserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(changeUserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                                .addGroup(changeUserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(changeUserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(currentUserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                        .addGroup(changeUserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(changeButton))
                            .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(jLabel3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(newUserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        changeUserNamePanelLayout.setVerticalGroup(
            changeUserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(changeUserNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentUserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(changeUserNamePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newUserNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changeUserNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(changeUserNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void currentUserNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentUserNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentUserNameTextActionPerformed

    private void newUserNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUserNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newUserNameTextActionPerformed

    //runs when the user presses the change button (looks like a send button)
    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        try {
            //if the text in the text area is not empty (ie there is a name inputted into the text field) then run the code
            if(!newUserNameText.getText().equals("")){
                   //make a new arraylist of names by getting all the names in the B column starting at row 2
                   ArrayList<String> names = getCellRange("B2","B");
                   
                   //if the username the use wishes to change their name to already exists in the array then let them know the user already exists
                   if (names.contains(newUserNameText.getText())){
                       newUserNameText.setText("USER ALREADY EXISTS");
                       
                   //if the user does not already exist, then run the following code    
                   }else{
                        //run the new username method, passing it the text in the text field
                        arcadeGUI.newUserName(newUserNameText.getText());
                        //dispose the window
                        this.dispose();
                   }
               }
        } catch (IOException ex) {
            Logger.getLogger(changeUserNameGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    //runs when the user types a key in the text field
    private void newUserNameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_newUserNameTextKeyPressed
       //if the user presses the enter key then run the new username method, passing it the text in the text field, along with the same if statement as the changeButtonActionPerformed method
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           try {
               if(!newUserNameText.getText().equals("")){
                   //make a new arraylist of names by getting all the names in the B column starting at row 2
                   ArrayList<String> names = getCellRange("B2","B");
                   
                   //if the username the use wishes to change their name to already exists in the array then let them know the user already exists
                   if (names.contains(newUserNameText.getText())){
                       newUserNameText.setText("USER ALREADY EXISTS");
                       
                   //if the user does not already exist, then run the following code    
                   }else{
                        //run the new username method, passing it the text in the text field
                        arcadeGUI.newUserName(newUserNameText.getText());
                        //dispose the window
                        this.dispose();
                   }
               }
           } catch (IOException ex) {
               Logger.getLogger(changeUserNameGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_newUserNameTextKeyPressed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(changeUserNameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(changeUserNameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(changeUserNameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(changeUserNameGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new changeUserNameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JPanel changeUserNamePanel;
    private javax.swing.JTextField currentUserNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField newUserNameText;
    private javax.swing.JTextField userIDText;
    // End of variables declaration//GEN-END:variables
}
